service: ${self:custom.project}-ksqldb

frameworkVersion: "3"

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-plugin-scripts
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-iam-helper"
  - "@stratiformdigital/serverless-idempotency-helper"
  - "@stratiformdigital/serverless-s3-security-helper"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:REGION_A}
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}
  iam:
    role:
      path: /delegatedadmin/developer/
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/cms-cloud-admin/developer-boundary-policy
      managedPolicies:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      statements:
        - Effect: "Allow"
          Action:
            - s3:PutObject
          Resource:
            - !Sub "${DdlBucket.Arn}"
            - !Sub "${DdlBucket.Arn}/*"
        - Effect: "Allow"
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - !Sub "arn:aws:secretsmanager:${self:provider.region}:${AWS::AccountId}:secret:${self:custom.project}*"
            - !Sub "arn:aws:secretsmanager:${self:provider.region}:${AWS::AccountId}:secret:ecr/images*"
        - Effect: "Allow"
          Action:
            - ssm:GetParameter
          Resource:
            - !Sub "arn:aws:ssm:${self:provider.region}:${AWS::AccountId}:parameter/aws/reference/secretsmanager/${self:custom.project}*"
            - !Sub "arn:aws:ssm:${self:provider.region}:${AWS::AccountId}:parameter/aws/reference/secretsmanager/ecr/images*"

custom:
  project: ${env:PROJECT}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - production
  vpc: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/vpc}
  ksqldbImage: ${ssm:/aws/reference/secretsmanager/ecr/images/${self:custom.project}/${self:service}, "confluentinc/ksqldb-server:0.26.0"}
  brokerString: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/brokerString}
  headlessSqlContents: ${file(./compileDDL.js):ddl}
  scripts:
    commands:
      connect: |
        runningInteractiveTasks=(`aws --region ${self:provider.region} ecs list-tasks --cluster ${self:service}-${sls:stage}-connect --service-name ksqldb-interactive --desired-status RUNNING | jq -r ".taskArns[]"`)
        runningHeadlessTasks=(`aws --region ${self:provider.region} ecs list-tasks --cluster ${self:service}-${sls:stage}-connect --service-name ksqldb-headless --desired-status RUNNING | jq -r ".taskArns[]"`)
        echo "\nThe following command(s) may be used to exec onto running fargate tasks.  Note, if there are no commands shown, there are no runnings tasks:"
        for task in "${runningInteractiveTasks[@]}"
        do
          echo "INTERACTIVE tasks:"
          echo aws --region ${self:provider.region} ecs execute-command --cluster ${self:service}-${sls:stage}-connect --task ${task##*/} --container ksqldb-interactive --interactive --command "/bin/sh"
        done
        for task in "${runningHeadlessTasks[@]}"
        do
          echo "HEADLESS tasks:"
          echo aws --region ${self:provider.region} ecs execute-command --cluster ${self:service}-${sls:stage}-connect --task ${task##*/} --container ksqldb-headless --interactive --command "/bin/sh"
        done

functions:
  stageDdl:
    handler: handlers/stageDdl.handler
    timeout: 900
    maximumRetryAttempts: 0
    environment:
      ddlBucket: !Ref DdlBucket
  cleanupKafka:
    handler: handlers/cleanupKafka.handler
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds: ${self:custom.vpc.privateSubnets}

resources:
  Resources:
    DdlBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

    StageDdl:
      Type: AWS::CloudFormation::CustomResource
      Properties:
        ServiceToken: !GetAtt StageDdlLambdaFunction.Arn
        DdlBucket: !Ref DdlBucket
        SqlContents: ${self:custom.headlessSqlContents}

    KsqlDBCluster:
      Type: AWS::ECS::Cluster
      Properties:
        ClusterName: ${self:service}-${sls:stage}-cluster
        ClusterSettings:
          - Name: containerInsights
            Value: enabled

    KsqlDBTaskDefinition:
      Type: AWS::ECS::TaskDefinition
      Properties:
        Family: ${self:service}-${sls:stage}-ksqldb
        RequiresCompatibilities:
          - FARGATE
        NetworkMode: awsvpc
        Cpu: 2048
        Memory: 8192
        ExecutionRoleArn: !Ref IamRoleLambdaExecution
        TaskRoleArn: !Ref IamRoleLambdaExecution
        ContainerDefinitions:
          - Name: ksqldb-server
            Image: ${self:custom.ksqldbImage}
            Essential: true
            PortMappings:
              - ContainerPort: 8088
                Protocol: tcp
            Environment:
              - Name: KSQL_BOOTSTRAP_SERVERS
                Value: ${self:custom.brokerString}
              - Name: KSQL_LISTENERS
                Value: "http://0.0.0.0:8088"
              - Name: KSQL_KSQL_SERVICE_ID
                Value: ${self:service}-${sls:stage}-ksqldb
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-region: ${self:provider.region}
                awslogs-group: /ecs/${self:service}-${sls:stage}
                awslogs-stream-prefix: ksqldb

    KsqlDBService:
      Type: AWS::ECS::Service
      DependsOn: KsqlDBCluster
      Properties:
        Cluster: !Ref KsqlDBCluster
        TaskDefinition: !Ref KsqlDBTaskDefinition
        DesiredCount: 1
        LaunchType: FARGATE
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ${self:custom.vpc.privateSubnets}
            SecurityGroups:
              - !Ref KsqlDBSecurityGroup
            AssignPublicIp: DISABLED

    KsqlDBSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId: ${self:custom.vpc.id}
        GroupDescription: Allow ECS tasks to communicate internally and externally
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 8088
            ToPort: 8088
            CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0

    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Lambda security group
        VpcId: ${self:custom.vpc.id}

    LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /ecs/${self:service}-${sls:stage}
        RetentionInDays: 14

    ksqldbHeadlessLogGroup:
      Type: "AWS::Logs::LogGroup"
      Properties:
        LogGroupName: /aws/fargate/${self:service}-${sls:stage}-ksqldb-headless

    ksqldbHeadlessRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "ecs.amazonaws.com"
                  - "ecs-tasks.amazonaws.com"
              Action: "sts:AssumeRole"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        Policies:
          - PolicyName: s3Policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - S3:ListBucket
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - ssmmessages:CreateControlChannel
                    - ssmmessages:CreateDataChannel
                    - ssmmessages:OpenControlChannel
                    - ssmmessages:OpenDataChannel
                  Resource: "*"

    ksqldbHeadlessCluster:
      Type: "AWS::ECS::Cluster"
      Properties:
        ClusterName: ${self:service}-${sls:stage}-connect
        ClusterSettings:
          - Name: containerInsights
            Value: enabled

    ksqldbHeadlessTaskDefinition:
      Type: "AWS::ECS::TaskDefinition"
      Properties:
        ContainerDefinitions:
          - Name: ksqldb-headless
            Image: ${self:custom.ksqldbImage}
            Ulimits:
              - Name: "nofile"
                HardLimit: 1048576
                SoftLimit: 1048576
            User: "root"
            Command:
              - bash
              - "-c"
              - |
                export CONNECT_REST_HOST_NAME=`curl $ECS_CONTAINER_METADATA_URI_V4 | sed -e 's/.*IPv4Addresses":\["\(.*\)"\],"AttachmentIndex.*/\1/'` &&
                echo $CONNECT_REST_HOST_NAME self >> /etc/hosts &&
                echo "Headless ksqlDB task..." &&
                yum install unzip -y &&
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&
                unzip awscliv2.zip &&
                ./aws/install &&
                aws s3 cp s3://$DDL_BUCKET/$DDL_KEY . &&
                unzip $DDL_KEY &&
                mv combined.sql /home/appuser/headless.sql &&
                cat /home/appuser/headless.sql &&
                /usr/bin/docker/run
            Environment:
              - Name: DDL_BUCKET
                Value: !Ref DdlBucket
              - Name: DDL_KEY
                Value: !GetAtt StageDdl.S3Key
              - Name: KSQL_BOOTSTRAP_SERVERS
                Value: "${self:custom.brokerString}"
              - Name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
                Value: "true"
              - Name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
                Value: "true"
              - Name: KSQL_SECURITY_PROTOCOL
                Value: SSL
              - Name: KSQL_KSQL_INTERNAL_TOPIC_REPLICAS
                Value: 3
              - Name: KSQL_KSQL_INTERNAL_TOPIC_MIN_INSYNC_REPLICAS
                Value: 2
              - Name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR
                Value: 3
              - Name: KSQL_KSQL_STREAMS_REPLICATION_FACTOR
                Value: 3
              - Name: KSQL_KSQL_STREAMS_PRODUCER_ACKS
                Value: "all"
              - Name: KSQL_KSQL_STREAMS_TOPIC_MIN_INSYNC_REPLICAS
                Value: 2
              - Name: KSQL_KSQL_QUERIES_FILE
                Value: "/home/appuser/headless.sql"
              - Name: KSQL_KSQL_SERVICE_ID
                Value: "${self:service}-headless"
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-region: !Ref AWS::Region
                awslogs-group: !Ref ksqldbHeadlessLogGroup
                awslogs-stream-prefix: fargate
                awslogs-datetime-format: \[%Y-%m-%d %H:%M:%S,
        Family: ${self:service}-${sls:stage}-ksqldb-headless
        NetworkMode: awsvpc
        ExecutionRoleArn: !GetAtt ksqldbHeadlessRole.Arn
        TaskRoleArn: !GetAtt ksqldbHeadlessRole.Arn
        RequiresCompatibilities:
          - FARGATE
        Memory: 8192
        Cpu: 2048
        EphemeralStorage:
          SizeInGiB: 200

    ksqldbHeadlessService:
      Type: "AWS::ECS::Service"
      Properties:
        Cluster: !Ref ksqldbHeadlessCluster
        DeploymentConfiguration:
          DeploymentCircuitBreaker:
            Enable: true
            Rollback: false
          MaximumPercent: 100
          MinimumHealthyPercent: 0
        EnableExecuteCommand: true
        LaunchType: FARGATE
        ServiceName: ksqldb-headless
        DesiredCount: 1
        TaskDefinition: !Ref ksqldbHeadlessTaskDefinition
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
            SecurityGroups:
              - !Ref KsqlDBSecurityGroup
            Subnets: ${self:custom.vpc.privateSubnets}
