service: ${self:custom.project}-ksqlthree

frameworkVersion: "3"

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-plugin-scripts
  - serverless-stack-termination-protection
  - "@stratiformdigital/serverless-iam-helper"
  - "@stratiformdigital/serverless-idempotency-helper"
  - "@stratiformdigital/serverless-s3-security-helper"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION_A}
  stackTags:
    PROJECT: ${self:custom.project}
    SERVICE: ${self:service}
  iam:
    role:
      path: /delegatedadmin/developer/
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/cms-cloud-admin/developer-boundary-policy
      statements:
        - Effect: "Allow"
          Action:
            - s3:PutObject
          Resource:
            - !Sub "${DdlBucket.Arn}"
            - !Sub "${DdlBucket.Arn}/*"

custom:
  project: ${env:PROJECT}
  serverlessTerminationProtection:
    stages: # Apply CloudFormation termination protection for these stages
      - master
      - val
      - production
  vpc: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/vpc, ssm:/aws/reference/secretsmanager/${self:custom.project}/default/vpc}
  ksqldbImage: ${ssm:/aws/reference/secretsmanager/ecr/images/${self:custom.project}/${self:service}, "confluentinc/ksqldb-server:0.28.2"}
  brokerString: ${ssm:/aws/reference/secretsmanager/${self:custom.project}/${sls:stage}/brokerString, ssm:/aws/reference/secretsmanager/${self:custom.project}/default/brokerString}
  headlessSqlContents: ${file(./compileDDL.js):ddl}
  scripts:
    hooks:
      package:initialize: |
        set -e
        set -x
        mkdir -p .ddl
        echo "${self:custom.headlessSqlContents}" > .ddl/combined.sql
    commands:
      connect: |
        runningHeadlessTasks=(`aws --region ${self:provider.region} ecs list-tasks --cluster ${self:service}-${sls:stage}-connect --service-name ksqldb-headless --desired-status RUNNING | jq -r ".taskArns[]"`)
        echo "\nThe following command(s) may be used to exec onto running fargate tasks.  Note, if there are no commands shown, there are no runnings tasks:"
        for task in "${runningHeadlessTasks[@]}"
        do
          echo "HEADLESS tasks:"
          echo aws --region ${self:provider.region} ecs execute-command --cluster ${self:service}-${sls:stage}-connect --task ${task##*/} --container ksqldb-headless --interactive --command "/bin/sh"
        done

params:
  master:
    cpu: 8192
    heap: "-Xms15G -Xmx15G"
    memory: 32768
    rocksdbCache: 11453246122
    topicNamespace: ""
  val:
    cpu: 8192
    heap: "-Xms15G -Xmx15G"
    memory: 32768
    rocksdbCache: 11453246122
    topicNamespace: ""
  production:
    cpu: 8192
    heap: "-Xms15G -Xmx15G"
    memory: 32768
    rocksdbCache: 11453246122
    topicNamespace: ""
  default:
    cpu: 2048
    heap: "-Xms4G -Xmx4G"
    memory: 8192
    rocksdbCache: 2147483648
    topicNamespace: --${self:custom.project}--${sls:stage}--

layers:
  ddl:
    name: ${self:service}-${sls:stage}
    path: ./.ddl

functions:
  stageDdl:
    handler: handlers/stageDdl.handler
    layers:
      - !Ref DdlLambdaLayer
    timeout: 900
    maximumRetryAttempts: 0
    environment:
      ddlBucket: !Ref DdlBucket
  cleanupKafka:
    handler: handlers/cleanupKafka.handler
    vpc:
      securityGroupIds:
        - Ref: LambdaSecurityGroup
      subnetIds: >-
        ${self:custom.vpc.privateSubnets}
    timeout: 300

resources:
  Conditions:
    isDev:
      Fn::Not:
        - Fn::Equals:
            - ${param:topicNamespace}
            - ""
  Resources:
    StageDdl:
      Type: AWS::CloudFormation::CustomResource
      Properties:
        ServiceToken: !GetAtt StageDdlLambdaFunction.Arn
        DdlBucket: !Ref DdlBucket
        TopicNamespace: ${param:topicNamespace}
        LayerVersion: !Ref DdlLambdaLayer
    ksqldbHeadlessLogGroup:
      Type: "AWS::Logs::LogGroup"
      Properties:
        LogGroupName: /aws/fargate/${self:service}-${sls:stage}-ksqldb-headless
    ksqldbSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security Group for the Fargate
        VpcId: ${self:custom.vpc.id}
    ksqldbSecurityGroupEgress:
      Type: AWS::EC2::SecurityGroupEgress
      Properties:
        GroupId: !Ref ksqldbSecurityGroup
        IpProtocol: -1
        CidrIp: 0.0.0.0/0
    ksqldbSecurityGroupIngressCluster:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupId: !Ref ksqldbSecurityGroup
        IpProtocol: tcp
        FromPort: 8088
        ToPort: 8088
        SourceSecurityGroupId: !Ref ksqldbSecurityGroup
    ksqldbHeadlessRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "ecs.amazonaws.com"
                  - "ecs-tasks.amazonaws.com"
              Action: "sts:AssumeRole"
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        Policies:
          - PolicyName: s3Policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - s3:GetObject
                    - S3:ListBucket
                  Resource: "*"
                  Policies:
                - Effect: Allow
                  Action:
                    - ssmmessages:CreateControlChannel
                    - ssmmessages:CreateDataChannel
                    - ssmmessages:OpenControlChannel
                    - ssmmessages:OpenDataChannel
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - ecr:BatchGetImage
                  Resource: !Sub "arn:aws:ecr:${self:provider.region}:${AWS::AccountId}:repository/*"

    ksqldbHeadlessTaskDefinition:
      Type: "AWS::ECS::TaskDefinition"
      Properties:
        ContainerDefinitions:
          - Name: ksqldb-headless
            Image: ${self:custom.ksqldbImage}
            Ulimits:
              - Name: "nofile"
                HardLimit: 1048576
                SoftLimit: 1048576
            User: "root"
            Command:
              - bash
              - "-c"
              - |
                export CONNECT_REST_HOST_NAME=`curl $ECS_CONTAINER_METADATA_URI_V4 | sed -e 's/.*IPv4Addresses":\["\(.*\)"\],"AttachmentIndex.*/\1/'` &&
                echo $CONNECT_REST_HOST_NAME self >> /etc/hosts &&
                echo "Headless ksqlDB task..." &&
                yum install unzip -y &&
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&
                unzip awscliv2.zip &&
                ./aws/install &&
                aws s3 cp s3://$DDL_BUCKET/$DDL_KEY . &&
                unzip $DDL_KEY &&
                mv combined.sql /home/appuser/headless.sql &&
                cat /home/appuser/headless.sql &&
                wget https://ksqldb-maven.s3-us-west-2.amazonaws.com/maven/io/confluent/ksql/ksql-rocksdb-config-setter/0.7.1/ksql-rocksdb-config-setter-0.7.1.jar -O /usr/share/java/ksqldb-rest-app/ksql-rocksdb-config-setter-0.7.1.jar &&
                echo "ksql.streams.rocksdb.config.setter=io.confluent.ksql.rocksdb.KsqlBoundedMemoryRocksDBConfigSetter" >> /etc/ksqldb/ksqldb-server.properties &&
                echo "ksql.plugins.rocksdb.cache.size={param:rocksdbCache}" >> /etc/ksqldb/ksqldb-server.properties &&
                echo "ksql.plugins.rocksdb.write.buffer.cache.use=true" >> /etc/ksqldb/ksqldb-server.properties &&
                echo "ksql.plugins.rocksdb.num.background.threads=1" >> /etc/ksqldb/ksqldb-server.properties &&
                /usr/bin/docker/run
            Environment:
              - Name: DDL_BUCKET
                Value: !Ref DdlBucket
              - Name: DDL_KEY
                Value: !GetAtt StageDdl.S3Key
              - Name: KSQL_BOOTSTRAP_SERVERS
                Value: "${self:custom.brokerString}"
              - Name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
                Value: "true"
              - Name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
                Value: "true"
              - Name: KSQL_SECURITY_PROTOCOL
                Value: SSL
              - Name: KSQL_KSQL_INTERNAL_TOPIC_REPLICAS
                Value: 3
              - Name: KSQL_KSQL_INTERNAL_TOPIC_MIN_INSYNC_REPLICAS
                Value: 2
              - Name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR
                Value: 3
              - Name: KSQL_KSQL_STREAMS_REPLICATION_FACTOR
                Value: 3
              - Name: KSQL_KSQL_STREAMS_PRODUCER_ACKS
                Value: "all"
              - Name: KSQL_KSQL_STREAMS_TOPIC_MIN_INSYNC_REPLICAS
                Value: 2
              - Name: KSQL_KSQL_QUERIES_FILE
                Value: "/home/appuser/headless.sql"
              - Name: KSQL_KSQL_SERVICE_ID
                Value: "${param:topicNamespace}${self:service}-headless"
              - Name: KSQL_KSQL_STREAMS_PRODUCER_DELIVERY_TIMEOUT_MS
                Value: 2147483647
              - Name: KSQL_KSQL_STREAMS_PRODUCER_MAX_BLOCK_MS
                Value: 9223372036854774000
              - Name: KSQL_CLASSPATH
                Value: "/usr/share/java/ksqldb-rest-app/*"
              - Name: KSQL_HEAP_OPTS
                Value: ${param:heap}
            LogConfiguration:
              LogDriver: awslogs
              Options:
                awslogs-region: !Ref AWS::Region
                awslogs-group: !Ref ksqldbHeadlessLogGroup
                awslogs-stream-prefix: fargate
                awslogs-datetime-format: \[%Y-%m-%d %H:%M:%S,
        Family: ${self:service}-${sls:stage}-ksqldb-headless
        NetworkMode: awsvpc
        ExecutionRoleArn: !GetAtt ksqldbHeadlessRole.Arn
        TaskRoleArn: !GetAtt ksqldbHeadlessRole.Arn
        RequiresCompatibilities:
          - FARGATE
        Memory: ${param:memory}
        Cpu: ${param:cpu}
        EphemeralStorage:
          SizeInGiB: 200
        Tags:
          - Key: ConditionalDependencyHack # Ensures order based on a conditioanl resource
            Value:
              Fn::If:
                - isDev
                - !Ref CleanupTopics
                - Blank

    ksqldbHeadlessCluster:
      Type: "AWS::ECS::Cluster"
      Properties:
        ClusterName: ${self:service}-${sls:stage}-connect
        ClusterSettings:
          - Name: containerInsights
            Value: enabled
    ksqldbHeadlessService:
      Type: "AWS::ECS::Service"
      Properties:
        Cluster: !Ref ksqldbHeadlessCluster
        DeploymentConfiguration:
          DeploymentCircuitBreaker:
            Enable: true
            Rollback: false
          MaximumPercent: 100
          MinimumHealthyPercent: 0
        EnableExecuteCommand: true
        LaunchType: FARGATE
        ServiceName: ksqldb-headless
        DesiredCount: 1
        TaskDefinition: !Ref ksqldbHeadlessTaskDefinition
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
            SecurityGroups:
              - !Ref ksqldbSecurityGroup
            Subnets: >-
              ${self:custom.vpc.privateSubnets}
    ECSFailureEventRule:
      Type: AWS::Events::Rule
      Properties:
        Description: "ksqlDB Cluster Task Failure Event Rule"
        EventPattern:
          account:
            - !Ref AWS::AccountId
          source:
            - "aws.ecs"
            - "demo.cli" # used to test events from the command line
          detail-type:
            - "ECS Task State Change"
          detail:
            lastStatus:
              - "STOPPED"
            stoppedReason:
              - "Essential container in task exited"
              - "Task failed container health checks"
            clusterArn:
              - !GetAtt ksqldbHeadlessCluster.Arn
        Targets:
          - Arn: ${param:ecsFailureTopicArn}
            Id: "KsqlDbEcsTaskFailure"
            InputTransformer:
              InputPathsMap:
                "clusterArn": "$.detail.clusterArn"
                "status": "$.detail.lastStatus"
                "account": "$.account"
                "stoppedReason": "$.detail.stoppedReason"
              InputTemplate: |
                "A KsqlDB Cluster Task Failure Event has occured. Account: <account> Cluster ARN: <clusterArn> Status: <status> Reason: <stoppedReason>"

    CleanupTopics:
      Type: AWS::CloudFormation::CustomResource
      Condition: isDev # We only clean up topics in lower environments where isDev is true
      Properties:
        ServiceToken: !GetAtt CleanupKafkaLambdaFunction.Arn
        BrokerString: ${self:custom.brokerString}
        TopicPatternsToDelete:
          - ${param:topicNamespace}aws.seatool.ksql.onemac.three.agg*
          - ${param:topicNamespace}aws.seatool.ksql.onemac.three.tld*
          - _confluent-ksql-${param:topicNamespace}${self:service}-*
          - ${param:topicNamespace}${self:service}*
      DependsOn:
        - LambdaSecurityGroupEgress

    ksqldbHeadlessServiceECSCpuAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${sls:stage}-ksqldbHeadlessService-CPUUtilization
        AlarmDescription: "Trigger an alarm when the CPU utilization reaches 80%"
        Namespace: AWS/ECS
        MetricName: CPUUtilization
        Dimensions:
          - Name: ClusterName
            Value: !Ref ksqldbHeadlessCluster
          - Name: ServiceName
            Value: !GetAtt ksqldbHeadlessService.Name
        Statistic: Average
        Period: 300
        EvaluationPeriods: 3
        Threshold: 80
        ComparisonOperator: GreaterThanOrEqualToThreshold
        AlarmActions:
          - ${param:ecsFailureTopicArn}
        OKActions:
          - ${param:ecsFailureTopicArn}
    ksqldbHeadlessServiceECSMemoryAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: ${self:service}-${sls:stage}-ksqldbHeadlessService-MemoryUtilization
        AlarmDescription: "Trigger an alarm when the Memory utilization reaches 75%"
        Namespace: AWS/ECS
        MetricName: MemoryUtilization
        Dimensions:
          - Name: ClusterName
            Value: !Ref ksqldbHeadlessCluster
          - Name: ServiceName
            Value: !GetAtt ksqldbHeadlessService.Name
        Statistic: Average
        Period: 60
        EvaluationPeriods: 2
        Threshold: 75
        ComparisonOperator: GreaterThanOrEqualToThreshold
        AlarmActions:
          - ${param:ecsFailureTopicArn}
        OKActions:
          - ${param:ecsFailureTopicArn}
    LambdaSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security Group for the topics lambda function
        VpcId: ${self:custom.vpc.id}
    LambdaSecurityGroupEgress:
      Type: AWS::EC2::SecurityGroupEgress
      Properties:
        GroupId: !Ref LambdaSecurityGroup
        IpProtocol: -1
        CidrIp: 0.0.0.0/0
    DdlBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${self:service}-${sls:stage}-ddl-${AWS::AccountId}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
  Outputs:
    KsqlDdlBucket:
      Value: !Ref DdlBucket
    KsqlDdlKey:
      Value: !GetAtt StageDdl.S3Key
