name: Create Release PR - val

on:
  workflow_run:
    workflows: ["Deploy"]
    types:
      - completed
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: val
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Release to val
          pr_body: |
            Release to val.

            #### Please **create a merge commit**
